### ISSUE TITLE
Version pinning is still to specific

### ISSUE THREAD

**Issue by kees-cambrian** [mattyait/terraform-aws-network-firewall#14]
│ Could not retrieve the list of available versions for provider
│ hashicorp/aws: locked provider registry.terraform.io/hashicorp/aws 4.66.1
│ does not match configured version constraint >= 3.28.0, ~> 4.0, >= 4.4.0,
│ ~> 4.50.0; must use terraform init -upgrade to allow selection of new
│ versions

**Comment by kees-cambrian** [comment]
I tested it with version 4.66.1 it works fine. This is how I changed the versions.tf:
```
terraform {
  required_version = ">=1.0.3"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.50.0"
    }
  }
}
```

**Comment by hungran** [comment]
I believed this issue was fixed by this?

https://github.com/mattyait/terraform-aws-network-firewall/pull/13
