### ISSUE TITLE
cannot see source IPs for domain stateful group

### ISSUE THREAD

**Issue by bigred247** [mattyait/terraform-aws-network-firewall#15]
Hi All,
I'm attempting to create a `domain_stateful_rule_group` with the below configuration but want to include some source IPs. After successfully running a terraform apply, I find the rule group gets created but cannot see the IPs below listed in the `Source IPs `section in the AWS console. Is there something I am missing here?

For the record, I have also tried the example domain rule found in the examples/domain-rule folder in the repo but this resulted in a similar issue.

```
    #Domain Firewall Rule Group
    domain_stateful_rule_group = [
      {
        capacity    = 100
        name        = "domain-rule-group-01"
        description = "Stateful rule for dev domain"
        domain_list = ["dev.example.com", "sftp.dev.example.com"]
        actions     = "DENYLIST"
        protocols   = ["HTTP_HOST", "TLS_SNI"]
        rule_variables = {
          ip_sets = [{
            key    = "WEBSERVERS_HOSTS"
            ip_set = ["10.0.0.0/16", "10.0.1.0/24", "192.168.0.0/16"]
            },
            {
              key    = "EXTERNAL_HOST"
              ip_set = ["0.0.0.0/0"]
            }
          ]
          port_sets = [
            {
              key       = "HTTP_PORTS"
              port_sets = ["443", "80"]
            }
          ]
        }
      },
    ]
```

**Comment by kerashanog** [comment]
To add more source IPs you can try add `rule_variables` with `key = HOME_NET` like this:
```
rule_variables = {
  ip_sets = [{
	  key = "HOME_NET"   #https://docs.aws.amazon.com/network-firewall/latest/developerguide/stateful-rule-groups-domain-names.html#stateful-rule-groups-domain-names-home-net
	  ip_set = ["10.0.0.0/8"]  #Add this rule_variables if traffic is flowing from other VPC
	},
	{
	  key    = "WEBSERVERS_HOSTS"
	  ip_set = ["10.0.0.0/16", "10.0.1.0/24", "192.168.0.0/16"]
	},
	{
	  key    = "EXTERNAL_HOST"
	  ip_set = ["0.0.0.0/0"]
	}
  ]
  port_sets = [
	{
	  key       = "HTTP_PORTS"
	  port_sets = ["443", "80"]
	}
  ]
}
```

**Comment by fraz78** [comment]
@kerashanog thanks for the feedback. 

After adding in the block below,  i can now see IPs listed in the source IPs in the console. 

```
        {
          key = "HOME_NET"   
	  ip_set = ["10.0.0.0/8"]  #Add this rule_variables if traffic is flowing from other VPC
	},
```
The other thing i noticed is that the CLI (see cmd below) is now showing the IP addresses associated with both the HOME_NET and WEBSERVERS_HOSTS ip_sets. Previously, it was not showing anything. This only happened after adding in the HOME_NET ip_set. Is this expected behaviour?

> aws network-firewall describe-rule-group --rule-group-arn arn:aws:network-firewall:eu-west-2:831604081234:stateful-rulegroup/domain-rule-group-01

This has resolved my problem so this issue can be closed.
