### ISSUE TITLE
Unable to create stateless rules for non-tcp/udp protocols

### ISSUE THREAD

**Issue by ozmodiar192** [mattyait/terraform-aws-network-firewall#2]
The stateless rules in this module include parameters like tcp_flags and ports that are specific to the TCP and UDP protocols.  If you try to build stateless rules for non-TCP/UDP protocols, the module fails because those parameters are invalid.  I attempted to add dynamic blocks for each problematic parameter, however terraform is erroring on the tcp_flag because it isn't able to manage multiple rules where tcp_flag is set, or not set.  It doesn't like that the lists are different types (list and null).  

I had the following ideas to fix this but was ultimately unable to make it work:
1) Iterate over the list and conditionally add to a local based on the protocol in the nested map.
2) Do some checking in the for_each

Ultimately I just added a new resource for non-tcp-based rules and left out the source/dest ports and tcp_flag, but that feels cheap.  It would be nice to be able to pass in a single stateless rule list and have it automatically handle including/excluding the parameters.

**Comment by hungran** [comment]
https://github.com/mattyait/terraform-aws-network-firewall/pull/3
+1 if our PR can help you on this

**Comment by mattyait** [comment]
Thanks @hungran for the PR to cover this, I will merge it and release it with some changes.

**Comment by mattyait** [comment]
Closing this one as this is fixed in new version.
