### ISSUE TITLE
Feat req: auto release following commit convention

### ISSUE THREAD

**Issue by hungran** [mattyait/terraform-aws-network-firewall#4]
Hey @mattyait 
for future contribute, we would like to have auto release/tag base on commit convention?

**Comment by mattyait** [comment]
Thanks, I'm in process of adding the standards so that it will be easy to have contribution on this project.

**Comment by mattyait** [comment]
This req has been added, we have auto release process now.

**Comment by hungran** [comment]
thanks :) @mattyait
