### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jouyang-peraton** [mattyait/terraform-aws-network-firewall#7]
for_each = [
        for b in lookup(var.domain_stateful_rule_group[count.index], "rule_variables", {}) : b
        if length(b) > 0
      ]
not if length(b) > 1

**Comment by hungran** [comment]
@jouyang-peraton can you provide more details?

**Comment by mattyait** [comment]
@jouyang-peraton It would be nice to share some error you are getting or snippet of code you are trying.

**Comment by jouyang-peraton** [comment]
Line 80 in maint.tf. Update from "if length(b) > 1" to "if length(b) > 0"
