### ISSUE TITLE
stateful arn for aws managed rules -is it missing?

### ISSUE THREAD

**Issue by dingersoll722** [mattyait/terraform-aws-network-firewall#8]
I see the dynamic bloc at line 240 in main - but I don't see a local for stateful rule group reference in the local variables. Is this how I should be entering the aws managed stateful rules?

**Comment by hungran** [comment]
https://github.com/mattyait/terraform-aws-network-firewall/blob/master/locals.tf#L2
do you mean this
@dingersoll722 
```hcl
locals {
  this_stateful_group_arn  = concat(aws_networkfirewall_rule_group.suricata_stateful_group.*.arn, aws_networkfirewall_rule_group.domain_stateful_group.*.arn, aws_networkfirewall_rule_group.fivetuple_stateful_group.*.arn)
  this_stateless_group_arn = concat(aws_networkfirewall_rule_group.stateless_group.*.arn)
}
```

**Comment by dingersoll722** [comment]
Not really - I need to do the AWS managed rules - like -  arn:aws:network-firewall:us-west-2:aws-managed:stateful-rulegroup/AbusedLegitBotNetCommandAndControlDomainsActionOrder (and the like)

It's in the policy - I don't create any of those rule groups for these to then become a reference ?- it's not a domain or suricata or five tuple type because it's already there managed by AWS.

**Comment by mattyait** [comment]
@dingersoll722 this requirement has been merged [PR #9](https://github.com/mattyait/terraform-aws-network-firewall/pull/9) and created a release out of it.

**Comment by hungran** [comment]
thanks @mattyait  I was misunderstand his issue

**Comment by mattyait** [comment]
@hungran no worry mate 👍
